/** @type {import('./nav.trial.js').NavItem[]} */
export const adminNav = [
  { label: "Dashboard", href: "/admin-sowmya/dashboard", icon: "LayoutDashboard" },
  { label: "All Users", href: "/admin-sowmya/users", icon: "Users" },
  { label: "Members", href: "/admin-sowmya/members", icon: "ShieldCheck" },
  { label: "Trial Members", href: "/admin-sowmya/trial-members", icon: "UserCheck" },
  { label: "Delivery Agents", href: "/admin-sowmya/delivery-agents", icon: "Truck" },
  { label: "Supervisors", href: "/admin-sowmya/supervisors", icon: "ShieldAlert" },
  { label: "Recyclers", href: "/admin-sowmya/recyclers", icon: "Recycle" },
  { label: "Marketplace Moderation", href: "/admin-sowmya/marketplace", icon: "ShoppingBag" },
  { label: "Marketplace Orders", href: "/admin-sowmya/orders", icon: "ClipboardList" },
  { label: "Waste Pickups", href: "/admin-sowmya/pickups", icon: "FileText" },
  { label: "Wallet Ledger", href: "/admin-sowmya/wallet", icon: "Wallet" },
  { label: "Payments & Revenue", href: "/admin-sowmya/payments", icon: "CreditCard" },
  { label: "Rewards Catalog", href: "/admin-sowmya/rewards", icon: "Gift" },
  { label: "EcoPoints Ledger", href: "/admin-sowmya/ecopoints", icon: "Award" },
  { label: "Analytics Panel", href: "/admin-sowmya/analytics", icon: "BarChart3" },
  { label: "Performance Reports", href: "/admin-sowmya/reports", icon: "FileSpreadsheet" },
  { label: "System Notifications", href: "/admin-sowmya/notifications", icon: "Bell" },
  { label: "Audit Logs", href: "/admin-sowmya/audit-logs", icon: "History" },
  { label: "Roles & Permissions", href: "/admin-sowmya/roles", icon: "Lock" },
  { label: "System Settings", href: "/admin-sowmya/settings", icon: "Settings" },
  { label: "My Profile", href: "/admin-sowmya/profile", icon: "User" },
];
